#ifndef __NEO_VM_ASTDEF__
#define __NEO_VM_ASTDEF__
enum NEO_AST_TYPE {
  NEO_AST_TYPE_NULL = 0,
  NEO_AST_TYPE_BOOLEAN,
  NEO_AST_TYPE_NUMBER,
  NEO_AST_TYPE_STRING,
  NEO_AST_TYPE_SYMBOL,
  NEO_AST_TYPE_REGEX,
  NEO_AST_TYPE_TEMPLATE_STRING,
  NEO_AST_TYPE_FUNCTION,
  NEO_AST_TYPE_LAMBDA,
  NEO_AST_TYPE_CLASS,
  NEO_AST_TYPE_ARRAY,
  NEO_AST_TYPE_OBJECT,
  NEO_AST_TYPE_EXPRESSION,
  NEO_AST_TYPE_MEMBER,
  NEO_AST_TYPE_CALL,
  NEO_AST_TYPE_PROGRAM,
  NEO_AST_TYPE_STATEMENTS,
  NEO_AST_TYPE_VAR,
  NEO_AST_TYPE_IF_STATEMENT,
  NEO_AST_TYPE_SWITCH_STATEMENT,
  NEO_AST_TYPE_FOR_STATEMENT,
  NEO_AST_TYPE_WHILE_STATEMENT,
  NEO_AST_TYPE_BRACKETS,
  NEO_AST_TYPE_MAX
};
#endif
