#ifndef __NEO_COMPILER_TOKENDEF__
#define __NEO_COMPILER_TOKENDEF__
typedef enum NEO_TOKEN_TYPE {
  NEO_TOKEN_TYPE_STRING = 0,
  NEO_TOKEN_TYPE_SYMBOL,
  NEO_TOKEN_TYPE_NUMBER,
  NEO_TOKEN_TYPE_WORD,
  NEO_TOKEN_TYPE_COMMENT,
  NEO_TOKEN_TYPE_REGEX,
  NEO_TOKEN_TYPE_MAX
} NEO_TOKEN_TYPE;
#endif