#ifndef __NEO_ENGINE_TYPEDEF__
#define __NEO_ENGINE_TYPEDEF__
enum NEO_VALUE_TYPE {
  NEO_TYPE_NULL = 0,
  NEO_TYPE_BOOLEAN,
  NEO_TYPE_NUMBER,
  NEO_TYPE_STRING,
  NEO_TYPE_ARRAY,
  NEO_TYPE_OBJECT,
  NEO_TYPE_EXCEPTION,
  NEO_TYPE_PROMISE,
  NEO_TYPE_FUNCTION,
  NEO_TYPE_MAX
};
#endif