#ifndef __NEO_VM_RESOLVERDEF__
#define __NEO_VM_RESOLVERDEF__
enum NEO_RESOLVER_TYPE {
  NEO_RESOLVER_TYPE_INTEGER = 0,
  NEO_RESOLVER_TYPE_FLOAT,
  NEO_RESOLVER_TYPE_STRING,
  NEO_RESOLVER_TYPE_SYMBOL,
};
#endif