#ifndef __NEO_VM_TYPE__
#define __NEO_VM_TYPE__
#include "runtime.h"
#define NEO_VM_TYPE_NULL NEO_TYPE_NULL
#define NEO_VM_TYPE_EXCEPTION NEO_TYPE_EXCEPTION
#define NEO_VM_TYPE_PROMISE NEO_TYPE_PROMISE
#define NEO_VM_TYPE_FUNCTION NEO_TYPE_FUNCTION
#define NEO_VM_TYPE_BOOLEAN 4
#define NEO_VM_TYPE_INTEGER 5
#define NEO_VM_TYPE_FLOAT 6
#define NEO_VM_TYPE_STRING 7
#define NEO_VM_TYPE_OBJECT 8
#define NEO_VM_TYPE_ARRAY 9
#define NEO_VM_TYPE_CUSTOM 10
extern const char *typename[];
#endif